// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Archivist",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "Domain", targets: ["Domain"]),
        .library(name: "ArchiveDomainServices", targets: ["ArchiveDomainServices"]),
        .library(name: "ArchiveSecurity", targets: ["ArchiveSecurity"]),
        .library(name: "BackendProtocol", targets: ["BackendProtocol"]),
        .library(name: "SevenZipProcessBackend", targets: ["SevenZipProcessBackend"]),
        .library(name: "LibarchiveBackend", targets: ["LibarchiveBackend"]),
        .library(name: "XIPStack", targets: ["XIPStack"]),
        .library(name: "BackendRegistry", targets: ["BackendRegistry"]),
        .library(name: "CrashSafeFilesystem", targets: ["CrashSafeFilesystem"]),
        .library(name: "ArchiveApplication", targets: ["ArchiveApplication"]),
        .library(name: "ArchiveCLI", targets: ["ArchiveCLI"]),
        .library(name: "ArchiveUI", targets: ["ArchiveUI"]),
        .library(name: "ProductionComposition", targets: ["ProductionComposition"]),
        .library(name: "FinderIntegration", targets: ["FinderIntegration"]),
        .executable(name: "archiveutil", targets: ["archiveutil"]),
        .executable(name: "ArchivistApp", targets: ["ArchivistApp"]),
    ],
    targets: [
        .target(name: "Domain", path: "Packages/Domain/Sources/Domain"),
        .testTarget(name: "DomainTests", dependencies: ["Domain"], path: "Packages/Domain/Tests/DomainTests"),
        .target(name: "ArchiveDomainServices", dependencies: ["Domain"], path: "Packages/ArchiveDomainServices/Sources/ArchiveDomainServices"),
        .testTarget(name: "ArchiveDomainServicesTests", dependencies: ["ArchiveDomainServices", "Domain"], path: "Packages/ArchiveDomainServices/Tests/ArchiveDomainServicesTests"),
        .target(name: "ArchiveSecurity", dependencies: ["Domain"], path: "Packages/Security/Sources/Security"),
        .testTarget(name: "SecurityTests", dependencies: ["ArchiveSecurity", "Domain"], path: "Packages/Security/Tests/SecurityTests"),
        .target(name: "BackendProtocol", dependencies: ["Domain"], path: "Packages/ArchiveBackends/Sources/BackendProtocol"),
        .testTarget(name: "BackendProtocolTests", dependencies: ["BackendProtocol", "Domain"], path: "Packages/ArchiveBackends/Tests/BackendProtocolTests"),
        .target(name: "CPTYShim", path: "Packages/ArchiveBackends/Sources/CPTYShim", publicHeadersPath: "include"),
        .target(name: "SevenZipProcessBackend", dependencies: ["Domain", "BackendProtocol", "CPTYShim"], path: "Packages/ArchiveBackends/Sources/SevenZipProcessBackend"),
        .testTarget(name: "SevenZipProcessBackendTests", dependencies: ["SevenZipProcessBackend", "CPTYShim"], path: "Packages/ArchiveBackends/Tests/SevenZipProcessBackendTests"),
        .binaryTarget(name: "PinnedLibarchive", path: "Vendor/Libarchive/Libarchive.xcframework"),
        .target(name: "CLibarchiveShim", dependencies: ["PinnedLibarchive"], path: "Packages/ArchiveBackends/Sources/CLibarchiveShim", publicHeadersPath: "include",
                linkerSettings: [.linkedLibrary("z"), .linkedLibrary("bz2"), .linkedLibrary("lzma"), .linkedLibrary("iconv")]),
        .target(name: "LibarchiveBackend", dependencies: ["Domain", "ArchiveSecurity", "BackendProtocol", "CLibarchiveShim"], path: "Packages/ArchiveBackends/Sources/LibarchiveBackend"),
        .testTarget(name: "LibarchiveBackendTests", dependencies: ["LibarchiveBackend", "CLibarchiveShim"], path: "Packages/ArchiveBackends/Tests/LibarchiveBackendTests"),
        .target(name: "XIPStack", dependencies: ["Domain", "ArchiveSecurity", "BackendProtocol"], path: "Packages/ArchiveBackends/Sources/XIPStack",
                linkerSettings: [.linkedLibrary("AppleArchive"), .linkedLibrary("compression")]),
        .testTarget(name: "XIPStackTests", dependencies: ["XIPStack", "BackendProtocol", "Domain"], path: "Packages/ArchiveBackends/Tests/XIPStackTests"),
        .target(name: "BackendRegistry", dependencies: ["Domain", "ArchiveDomainServices", "BackendProtocol"], path: "Packages/ArchiveBackends/Sources/BackendRegistry"),
        .testTarget(name: "BackendRegistryTests", dependencies: ["BackendRegistry", "BackendProtocol", "Domain"], path: "Packages/ArchiveBackends/Tests/BackendRegistryTests"),
        .target(name: "CrashSafeFilesystem", dependencies: ["Domain"], path: "Packages/Filesystem/Sources/CrashSafeFilesystem"),
        .testTarget(name: "CrashSafeFilesystemTests", dependencies: ["CrashSafeFilesystem", "Domain"], path: "Packages/Filesystem/Tests/CrashSafeFilesystemTests"),
        .target(name: "ArchiveApplication", dependencies: ["Domain", "ArchiveSecurity", "BackendProtocol", "BackendRegistry", "CrashSafeFilesystem"], path: "Packages/Application/Sources/ArchiveApplication"),
        .testTarget(name: "ArchiveApplicationTests", dependencies: ["ArchiveApplication", "BackendProtocol", "BackendRegistry", "Domain"], path: "Packages/Application/Tests/ArchiveApplicationTests"),
        .target(name: "ArchiveCLI", dependencies: ["Domain"], path: "Packages/CLI/Sources/ArchiveCLI"),
        .testTarget(name: "ArchiveCLITests", dependencies: ["ArchiveCLI", "BackendProtocol", "Domain"], path: "Packages/CLI/Tests/ArchiveCLITests"),
        .executableTarget(name: "archiveutil", dependencies: ["ArchiveCLI", "ArchiveApplication", "BackendRegistry", "CrashSafeFilesystem", "SevenZipProcessBackend", "LibarchiveBackend", "XIPStack", "Domain"], path: "Packages/CLI/Sources/archiveutil"),
        .target(name: "ProductionComposition", dependencies: ["BackendRegistry", "SevenZipProcessBackend", "LibarchiveBackend", "XIPStack"], path: "Packages/App/Sources/ProductionComposition"),
        .target(name: "FinderIntegration", dependencies: ["Domain", "BackendProtocol"], path: "Packages/FinderIntegration/Sources/FinderIntegration"),
        .testTarget(name: "FinderIntegrationTests", dependencies: ["FinderIntegration", "Domain", "BackendProtocol"], path: "Packages/FinderIntegration/Tests/FinderIntegrationTests"),
        .target(name: "ArchiveUI", dependencies: ["ArchiveApplication", "BackendRegistry", "BackendProtocol", "CrashSafeFilesystem", "Domain", "FinderIntegration"], path: "Packages/App/Sources/ArchiveUI",
                linkerSettings: [.linkedFramework("QuickLookUI")]),
        .testTarget(name: "ArchiveUITests", dependencies: ["ArchiveUI", "ArchiveApplication", "BackendProtocol", "BackendRegistry", "Domain", "FinderIntegration"], path: "Packages/App/Tests/ArchiveUITests"),
        .executableTarget(name: "ArchivistApp", dependencies: ["ArchiveUI", "ProductionComposition"], path: "Packages/App/Sources/ArchivistApp"),
    ]
)
